# Module 0 — L'écosystème Data Python

> **Manipulation des données avec Pandas — Devenir Data Scientist**

# 18. 🧪 Mini-TP — Prise en main

Nous allons utiliser le DataFrame suivant :

In [2]:
import pandas as pd

In [3]:
data = {
    "name": [
        "Alice", "Bob", "Charlie",
        "David", "Emma", "Frank"
    ],
    "age": [32, 41, 27, 35, 29, 52],
    "city": [
        "Paris", "Lyon", "Paris",
        "Marseille", "Lyon", "Paris"
    ],
    "salary": [
        42000, 58000, 39000,
        51000, 45000, 72000
    ]
}

df = pd.DataFrame(data)

df

      name  age       city  salary
0    Alice   32      Paris   42000
1      Bob   41       Lyon   58000
2  Charlie   27      Paris   39000
3    David   35  Marseille   51000
4     Emma   29       Lyon   45000
5    Frank   52      Paris   72000

### Questions

**1. Combien y a-t-il de lignes et de colonnes ?**

In [4]:
df.shape

(6, 4)

**2. Quels sont les noms des colonnes ?**

In [5]:
df.columns

Index(['name', 'age', 'city', 'salary'], dtype='object')

**3. Quels sont les types des colonnes ?**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    6 non-null      object
 1   age     6 non-null      int64
 2   city    6 non-null      object
 3   salary  6 non-null      int64
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

In [7]:
df.dtypes

name      object
age        int64
city      object
salary     int64
dtype: object

**4. Affichez uniquement les colonnes `name` et `salary`.**

In [8]:
df[["name", "salary"]]

      name  salary
0    Alice   42000
1      Bob   58000
2  Charlie   39000
3    David   51000
4     Emma   45000
5    Frank   72000

**5. Quel est le salaire moyen ?**

In [9]:
df.salary.mean()

np.float64(51166.666666666664)

**6. Quels sont les employés de plus de 30 ans ?**

In [10]:
df[df["age"] > 30]

    name  age       city  salary
0  Alice   32      Paris   42000
1    Bob   41       Lyon   58000
3  David   35  Marseille   51000
5  Frank   52      Paris   72000

**7. Créez une colonne `salary_k` contenant le salaire en milliers d'euros.**

In [12]:
df["salary_k"] = df.salary / 1000
df

      name  age       city  salary  salary_k
0    Alice   32      Paris   42000      42.0
1      Bob   41       Lyon   58000      58.0
2  Charlie   27      Paris   39000      39.0
3    David   35  Marseille   51000      51.0
4     Emma   29       Lyon   45000      45.0
5    Frank   52      Paris   72000      72.0

# 19. 🧠 Challenge

Sans utiliser de boucle `for` :

> Trouvez les personnes de plus de 30 ans qui gagnent plus de 50 000 €.

Indice :

In [ ]:
df[
    (condition_1)
    & (condition_2)
]

In [13]:
df[(df["age"] > 30) & (df["salary"] > 50000)]

    name  age       city  salary  salary_k
1    Bob   41       Lyon   58000      58.0
3  David   35  Marseille   51000      51.0
5  Frank   52      Paris   72000      72.0

# 20. À retenir

### NumPy

> **Calcul numérique et tableaux multidimensionnels**

In [ ]:
np.array(...)

### Pandas Series

> **Une colonne de données**

In [ ]:
pd.Series(...)

### Pandas DataFrame

> **Une table de données**

In [ ]:
pd.DataFrame(...)

### Les opérations fondamentales

```text
Explorer
   ↓
Sélectionner
   ↓
Filtrer
   ↓
Transformer
   ↓
Agréger
   ↓
Combiner
   ↓
Analyser
```

# 21. La question importante

Un Data Scientist ne passe pas directement de :

```text
Données
   ↓
Modèle ML
```

Il passe généralement par :

```text
Données brutes
      ↓
   Comprendre
      ↓
   Nettoyer
      ↓
 Transformer
      ↓
   Analyser
      ↓
Feature Engineering
      ↓
 Dataset ML
      ↓
    Modèle
```

> **Une grande partie du travail de Data Science consiste à rendre les données exploitables.**

Et Pandas est l'un des outils principaux pour effectuer ce travail.

# 🚀 Suite du cours

Dans le prochain module, nous allons apprendre à **explorer et sélectionner efficacement les données**.

Nous verrons notamment :

```text
head()
tail()
shape
columns
dtypes
info()
describe()

        +

[]
[[]]
iloc
loc

        +

conditions
isin()
between()
query()
```

L'objectif sera de pouvoir prendre un dataset inconnu et répondre rapidement à la question :

> **"Qu'est-ce qu'il y a réellement dans ces données ?"**