# Module 1 — Explorer un jeu de données avec Pandas

> **Manipulation des données avec Pandas — Devenir Data Scientist**

## 🎯 Objectifs du module

À la fin de ce module, vous serez capables de :

* charger un jeu de données avec Pandas ;
* comprendre rapidement sa structure ;
* identifier les variables et leurs types ;
* sélectionner des colonnes ;
* sélectionner des lignes ;
* filtrer des observations ;
* combiner plusieurs conditions ;
* analyser des variables catégorielles ;
* produire des statistiques descriptives ;
* identifier les premiers problèmes de qualité des données ;
* adopter une démarche systématique face à un dataset inconnu.

# 1. Le travail commence rarement par un modèle

En Data Science, on imagine parfois le workflow suivant :

```text
Données
   ↓
Machine Learning
   ↓
Prédiction
```

Dans la réalité, le processus ressemble davantage à :

```text
                 Dataset
                    │
                    ↓
              Exploration
                    │
                    ↓
             Compréhension
                    │
                    ↓
              Nettoyage
                    │
                    ↓
           Transformation
                    │
                    ↓
        Feature Engineering
                    │
                    ↓
              Modélisation
```

Avant de construire un modèle, il faut donc répondre à des questions simples :

> Combien avons-nous d'observations ?

> Quelles sont les variables disponibles ?

> Quels sont leurs types ?

> Y a-t-il des valeurs manquantes ?

> Les valeurs semblent-elles cohérentes ?

> Quelles sont les catégories présentes ?

> Existe-t-il des valeurs aberrantes ?

> Quelles relations semblent intéressantes ?

# 2. Un réflexe de Data Scientist

Lorsqu'on reçoit un nouveau dataset, **ne commencez pas immédiatement à le transformer**.

Commencez par l'observer.

Une bonne séquence initiale est :

```text
1. Charger
      ↓
2. Regarder quelques lignes
      ↓
3. Comprendre les dimensions
      ↓
4. Examiner les colonnes
      ↓
5. Examiner les types
      ↓
6. Examiner les statistiques
      ↓
7. Chercher les valeurs manquantes
      ↓
8. Explorer les catégories
      ↓
9. Commencer à poser des questions
```

Cette séquence va devenir un réflexe.

# 3. Notre dataset

Nous allons travailler avec un jeu de données représentant des **commandes d'une boutique en ligne**.

Chaque ligne représente une commande.

Les variables disponibles sont :

| Colonne           | Description                |
| ----------------- | -------------------------- |
| `order_id`        | Identifiant de la commande |
| `customer_id`     | Identifiant du client      |
| `order_date`      | Date de la commande        |
| `country`         | Pays du client             |
| `category`        | Catégorie du produit       |
| `quantity`        | Quantité commandée         |
| `unit_price`      | Prix unitaire              |
| `discount`        | Remise appliquée           |
| `payment_method`  | Moyen de paiement          |
| `customer_rating` | Note donnée par le client  |

# 4. Importer Pandas

In [1]:
import pandas as pd

Vérifions la version utilisée :

In [2]:
pd.__version__

'2.2.3'

# 5. Charger les données

Dans un projet réel, les données peuvent provenir :

* d'un CSV ;
* d'un fichier Excel ;
* d'une base SQL ;
* d'une API ;
* d'un fichier JSON ;
* d'un data lake ;
* d'un autre DataFrame.

Ici, nous utiliserons un fichier CSV.

In [3]:
df = pd.read_csv("data/orders.csv")

# 6. Première observation : `head()`

La première chose à faire après avoir chargé un dataset :

In [4]:
df.head()

,order_id,customer_id,order_date,country,category,quantity,unit_price,discount,payment_method,customer_rating
0,ORD-004875,CUST-00286,2024-11-12 09:40:00,Germany,Electronics,8,847.65,0.2,Apple Pay,3.0
1,ORD-001026,CUST-00084,2025-09-11 12:22:00,Italy,Sports,2,166.25,0.0,Bank Transfer,3.0
2,ORD-003546,CUST-00947,2025-04-26 08:58:00,Italy,Home,3,500.00,0.1,Credit Card,3.0
3,ORD-003822,CUST-00017,2024-06-01 14:55:00,Belgium,Home,2,346.55,0.1,Credit Card,5.0
4,ORD-004395,CUST-00764,2024-01-26 12:23:00,Italy,Clothing,2,228.08,0.0,Bank Transfer,5.0

Par défaut, Pandas affiche les cinq premières lignes.

Nous pouvons demander davantage :

In [5]:
df.head(10)

,order_id,customer_id,order_date,country,category,quantity,unit_price,discount,payment_method,customer_rating
0,ORD-004875,CUST-00286,2024-11-12 09:40:00,Germany,Electronics,8,847.65,0.20,Apple Pay,3.0
1,ORD-001026,CUST-00084,2025-09-11 12:22:00,Italy,Sports,2,166.25,0.00,Bank Transfer,3.0
2,ORD-003546,CUST-00947,2025-04-26 08:58:00,Italy,Home,3,500.00,0.10,Credit Card,3.0
3,ORD-003822,CUST-00017,2024-06-01 14:55:00,Belgium,Home,2,346.55,0.10,Credit Card,5.0
4,ORD-004395,CUST-00764,2024-01-26 12:23:00,Italy,Clothing,2,228.08,0.00,Bank Transfer,5.0
5,ORD-003423,CUST-00901,2025-04-01 13:21:00,Netherlands,Home,3,500.00,0.10,PayPal,2.0
6,ORD-002418,CUST-00391,2024-08-20 12:14:00,France,Books,1,35.68,0.00,Bank Transfer,5.0
7,ORD-001096,CUST-00121,2024-01-25 01:22:00,Italy,Clothing,1,245.59,0.05,Credit Card,4.0
8,ORD-004460,CUST-00981,2025-07-05 11:39:00,Germany,Clothing,3,163.35,0.15,Credit Card,3.0
9,ORD-000706,CUST-00848,2025-11-07 12:37:00,Spain,Electronics,4,679.09,0.00,Apple Pay,5.0

## Pourquoi `head()` est-il important ?

Il permet de détecter immédiatement des problèmes évidents :

* noms de colonnes inattendus ;
* valeurs mal formatées ;
* séparateur incorrect ;
* données décalées ;
* valeurs étranges ;
* dates qui semblent incorrectes ;
* colonnes qui ne contiennent pas ce que l'on attend.

# 7. Observer la fin du dataset

In [6]:
df.tail()

,order_id,customer_id,order_date,country,category,quantity,unit_price,discount,payment_method,customer_rating
5010,ORD-004427,CUST-00386,2025-11-19 03:36:00,France,Books,1,37.46,0.15,PayPal,5.0
5011,ORD-000467,CUST-00249,2025-02-19 22:32:00,Germany,Sports,3,229.10,0.05,Credit Card,4.0
5012,ORD-003093,CUST-01079,2024-07-16 17:48:00,Germany,clothing,1,178.44,0.00,Bank Transfer,5.0
5013,ORD-003773,CUST-00792,2025-07-08 05:15:00,Spain,Electronics,2,1200.00,0.00,Credit Card,5.0
5014,ORD-000861,CUST-01453,2024-01-10 05:41:00,Germany,Clothing,1,183.05,0.05,Bank Transfer,5.0

Pourquoi regarder aussi les dernières lignes ?

Parce que certains problèmes peuvent apparaître uniquement à la fin du fichier.

# 8. Combien avons-nous de données ?

Utilisons `shape`.

In [7]:
df.shape

(5015, 10)

Le résultat est un tuple :

```text
(nombre_de_lignes, nombre_de_colonnes)
```

Par exemple :

```text
(10000, 10)
```

signifie :

> 10 000 observations et 10 variables.

## Extraire séparément les dimensions

In [8]:
rows, columns = df.shape

print("Nombre de lignes :", rows)
print("Nombre de colonnes :", columns)

Nombre de lignes : 5015
Nombre de colonnes : 10

# 9. Les noms des colonnes

In [9]:
df.columns

Index(['order_id', 'customer_id', 'order_date', 'country', 'category',
       'quantity', 'unit_price', 'discount', 'payment_method',
       'customer_rating'],
      dtype='object')

On peut également les transformer en liste :

In [10]:
list(df.columns)

['order_id',
 'customer_id',
 'order_date',
 'country',
 'category',
 'quantity',
 'unit_price',
 'discount',
 'payment_method',
 'customer_rating']

## 💡 Question

Pourquoi est-il important de vérifier les noms des colonnes ?

Imaginez que vous pensiez avoir :

```text
customer_id
```

mais que le dataset contienne réellement :

```text
Customer ID
```

ou :

```text
customerId
```

ou :

```text
customer_id
```

Pour Pandas, ce sont trois colonnes différentes.

# 10. Les types de données

In [11]:
df.dtypes

order_id            object
customer_id         object
order_date          object
country             object
category            object
quantity             int64
unit_price         float64
discount           float64
payment_method      object
customer_rating    float64
dtype: object

On peut par exemple obtenir :

```text
order_id              object
customer_id            int64
order_date            object
country               object
category              object
quantity               int64
unit_price           float64
discount             float64
payment_method        object
customer_rating      float64
```

# 11. Pourquoi les types sont-ils importants ?

Le type détermine en partie les opérations que nous pouvons effectuer.

Par exemple :

```text
int
    ↓
calculs numériques

float
    ↓
calculs numériques avec décimales

object / string
    ↓
texte

datetime
    ↓
dates et temps
```

Prenons une date :

In [12]:
df["order_date"].head()

0    2024-11-12 09:40:00
1    2025-09-11 12:22:00
2    2025-04-26 08:58:00
3    2024-06-01 14:55:00
4    2024-01-26 12:23:00
Name: order_date, dtype: object

Si elle est de type `object`, Pandas la considère essentiellement comme du texte.

Nous verrons dans un prochain module comment convertir correctement les dates.

# 12. `info()` : notre première commande de diagnostic

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5015 entries, 0 to 5014
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         5015 non-null   object
 1   customer_id      5015 non-null   object
 2   order_date       5015 non-null   object
 3   country          4995 non-null   object
 4   category         4985 non-null   object
 5   quantity         5015 non-null   int64
 6   unit_price       5015 non-null   float64
 7   discount         5015 non-null   float64
 8   payment_method   5015 non-null   object
 9   customer_rating  4615 non-null   float64
dtypes: float64(3), int64(1), object(6)
memory usage: 391.9+ KB

Cette commande est particulièrement utile.

Elle donne notamment :

* le nombre de lignes ;
* les noms des colonnes ;
* le nombre de valeurs non nulles ;
* les types ;
* une estimation de la mémoire utilisée.

## 🧠 Réflexe Data Scientist

Après avoir chargé un nouveau dataset :

In [14]:
df.head()
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5015 entries, 0 to 5014
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         5015 non-null   object
 1   customer_id      5015 non-null   object
 2   order_date       5015 non-null   object
 3   country          4995 non-null   object
 4   category         4985 non-null   object
 5   quantity         5015 non-null   int64
 6   unit_price       5015 non-null   float64
 7   discount         5015 non-null   float64
 8   payment_method   5015 non-null   object
 9   customer_rating  4615 non-null   float64
dtypes: float64(3), int64(1), object(6)
memory usage: 391.9+ KB

Ces trois commandes donnent déjà énormément d'informations.

# 13. Sélectionner une colonne

Pour récupérer une colonne :

In [15]:
df["country"]

0       Germany
1         Italy
2         Italy
3       Belgium
4         Italy
         ...
5010     France
5011    Germany
5012    Germany
5013      Spain
5014    Germany
Name: country, Length: 5015, dtype: object

Le résultat est une `Series`.

Vérifions :

In [16]:
type(df["country"])

pandas.core.series.Series

# 14. Sélectionner plusieurs colonnes

Pour sélectionner plusieurs colonnes, on utilise une liste :

In [17]:
df[["country", "category", "quantity"]]

      country     category  quantity
0     Germany  Electronics         8
1       Italy       Sports         2
2       Italy         Home         3
3     Belgium         Home         2
4       Italy     Clothing         2
...       ...          ...       ...
5010   France        Books         1
5011  Germany       Sports         3
5012  Germany     clothing         1
5013    Spain  Electronics         2
5014  Germany     Clothing         1

[5015 rows x 3 columns]

Attention à la différence :

In [18]:
df["country"]

0       Germany
1         Italy
2         Italy
3       Belgium
4         Italy
         ...
5010     France
5011    Germany
5012    Germany
5013      Spain
5014    Germany
Name: country, Length: 5015, dtype: object

et :

In [19]:
df[["country"]]

      country
0     Germany
1       Italy
2       Italy
3     Belgium
4       Italy
...       ...
5010   France
5011  Germany
5012  Germany
5013    Spain
5014  Germany

[5015 rows x 1 columns]

Le premier retourne une `Series`.

Le second retourne un `DataFrame`.

In [20]:
type(df["country"])

pandas.core.series.Series

In [21]:
type(df[["country"]])

pandas.core.frame.DataFrame

# 15. Une question métier

Imaginons que notre responsable marketing nous demande :

> "Je veux uniquement connaître le pays, la catégorie et le montant de chaque commande."

Nous devons d'abord créer le montant :

In [22]:
df["amount"] = df["quantity"] * df["unit_price"]

Puis sélectionner les colonnes utiles :

In [23]:
df[
    ["country", "category", "quantity", "amount"]
].head()

   country     category  quantity   amount
0  Germany  Electronics         8  6781.20
1    Italy       Sports         2   332.50
2    Italy         Home         3  1500.00
3  Belgium         Home         2   693.10
4    Italy     Clothing         2   456.16

# 16. Sélectionner une ligne avec `iloc`

`iloc` permet de sélectionner par **position**.

Première ligne :

In [24]:
df.iloc[0]

order_id                    ORD-004875
customer_id                 CUST-00286
order_date         2024-11-12 09:40:00
country                        Germany
category                   Electronics
quantity                             8
unit_price                      847.65
discount                           0.2
payment_method               Apple Pay
customer_rating                    3.0
amount                          6781.2
Name: 0, dtype: object

Deuxième ligne :

In [25]:
df.iloc[1]

order_id                    ORD-001026
customer_id                 CUST-00084
order_date         2025-09-11 12:22:00
country                          Italy
category                        Sports
quantity                             2
unit_price                      166.25
discount                           0.0
payment_method           Bank Transfer
customer_rating                    3.0
amount                           332.5
Name: 1, dtype: object

Dixième ligne :

In [26]:
df.iloc[9]

order_id                    ORD-000706
customer_id                 CUST-00848
order_date         2025-11-07 12:37:00
country                          Spain
category                   Electronics
quantity                             4
unit_price                      679.09
discount                           0.0
payment_method               Apple Pay
customer_rating                    5.0
amount                         2716.36
Name: 9, dtype: object

# 17. Sélectionner plusieurs lignes

Les slices fonctionnent comme avec les listes Python.

In [27]:
df.iloc[0:5]

,order_id,customer_id,order_date,country,category,quantity,unit_price,discount,payment_method,customer_rating,amount
0,ORD-004875,CUST-00286,2024-11-12 09:40:00,Germany,Electronics,8,847.65,0.2,Apple Pay,3.0,6781.20
1,ORD-001026,CUST-00084,2025-09-11 12:22:00,Italy,Sports,2,166.25,0.0,Bank Transfer,3.0,332.50
2,ORD-003546,CUST-00947,2025-04-26 08:58:00,Italy,Home,3,500.00,0.1,Credit Card,3.0,1500.00
3,ORD-003822,CUST-00017,2024-06-01 14:55:00,Belgium,Home,2,346.55,0.1,Credit Card,5.0,693.10
4,ORD-004395,CUST-00764,2024-01-26 12:23:00,Italy,Clothing,2,228.08,0.0,Bank Transfer,5.0,456.16

Les cinq premières lignes.

In [28]:
df.iloc[10:20]

,order_id,customer_id,order_date,country,category,quantity,unit_price,discount,payment_method,customer_rating,amount
10,ORD-002375,CUST-01049,2025-10-05 09:16:00,France,Clothing,1,216.20,0.00,Credit Card,4.0,216.20
11,ORD-000531,CUST-00898,2024-01-08 23:22:00,Spain,Sports,2,254.37,0.10,Credit Card,2.0,508.74
12,ORD-000801,CUST-00019,2025-06-28 21:05:00,France,Books,1,66.92,0.00,Bank Transfer,NaN,66.92
13,ORD-004525,CUST-01201,2025-03-18 20:04:00,Netherlands,Books,4,38.88,0.05,Apple Pay,3.0,155.52
14,ORD-001457,CUST-01477,2025-07-20 23:19:00,France,Books,3,51.87,0.20,PayPal,5.0,155.61
15,ORD-001392,CUST-00795,2025-01-04 10:54:00,Germany,Sports,4,340.39,0.10,PayPal,NaN,1361.56
16,ORD-003650,CUST-01107,2024-01-11 05:46:00,Germany,Electronics,1,607.94,0.20,Credit Card,4.0,607.94
17,ORD-003200,CUST-00398,2025-10-25 09:38:00,Germany,Electronics,1,241.71,0.00,PayPal,3.0,241.71
18,ORD-002672,CUST-01284,2025-11-20 06:02:00,Netherlands,Clothing,2,127.09,0.20,Credit Card,4.0,254.18
19,ORD-002813,CUST-00297,2025-01-18 15:21:00,France,Clothing,3,131.81,0.30,Credit Card,4.0,395.43

Les lignes 10 à 19.

## Sélectionner lignes et colonnes

In [29]:
df.iloc[0:5, 0:3]

     order_id customer_id           order_date
0  ORD-004875  CUST-00286  2024-11-12 09:40:00
1  ORD-001026  CUST-00084  2025-09-11 12:22:00
2  ORD-003546  CUST-00947  2025-04-26 08:58:00
3  ORD-003822  CUST-00017  2024-06-01 14:55:00
4  ORD-004395  CUST-00764  2024-01-26 12:23:00

Lecture :

> lignes 0 à 4, colonnes 0 à 2.

# 18. `loc` : sélectionner avec les labels

`loc` travaille avec les labels de l'index et des colonnes.

In [30]:
df.loc[0]

order_id                    ORD-004875
customer_id                 CUST-00286
order_date         2024-11-12 09:40:00
country                        Germany
category                   Electronics
quantity                             8
unit_price                      847.65
discount                           0.2
payment_method               Apple Pay
customer_rating                    3.0
amount                          6781.2
Name: 0, dtype: object

Sélectionner certaines colonnes :

In [31]:
df.loc[:, ["country", "category"]]

      country     category
0     Germany  Electronics
1       Italy       Sports
2       Italy         Home
3     Belgium         Home
4       Italy     Clothing
...       ...          ...
5010   France        Books
5011  Germany       Sports
5012  Germany     clothing
5013    Spain  Electronics
5014  Germany     Clothing

[5015 rows x 2 columns]

Lecture :

```text
:
↓
toutes les lignes

["country", "category"]
↓
ces deux colonnes
```

# 19. `iloc` vs `loc`

Retenez pour l'instant :

```text
iloc
 ↓
position

loc
 ↓
label
```

Exemple :

In [32]:
df.iloc[0:10]

,order_id,customer_id,order_date,country,category,quantity,unit_price,discount,payment_method,customer_rating,amount
0,ORD-004875,CUST-00286,2024-11-12 09:40:00,Germany,Electronics,8,847.65,0.20,Apple Pay,3.0,6781.20
1,ORD-001026,CUST-00084,2025-09-11 12:22:00,Italy,Sports,2,166.25,0.00,Bank Transfer,3.0,332.50
2,ORD-003546,CUST-00947,2025-04-26 08:58:00,Italy,Home,3,500.00,0.10,Credit Card,3.0,1500.00
3,ORD-003822,CUST-00017,2024-06-01 14:55:00,Belgium,Home,2,346.55,0.10,Credit Card,5.0,693.10
4,ORD-004395,CUST-00764,2024-01-26 12:23:00,Italy,Clothing,2,228.08,0.00,Bank Transfer,5.0,456.16
5,ORD-003423,CUST-00901,2025-04-01 13:21:00,Netherlands,Home,3,500.00,0.10,PayPal,2.0,1500.00
6,ORD-002418,CUST-00391,2024-08-20 12:14:00,France,Books,1,35.68,0.00,Bank Transfer,5.0,35.68
7,ORD-001096,CUST-00121,2024-01-25 01:22:00,Italy,Clothing,1,245.59,0.05,Credit Card,4.0,245.59
8,ORD-004460,CUST-00981,2025-07-05 11:39:00,Germany,Clothing,3,163.35,0.15,Credit Card,3.0,490.05
9,ORD-000706,CUST-00848,2025-11-07 12:37:00,Spain,Electronics,4,679.09,0.00,Apple Pay,5.0,2716.36

signifie :

> les 10 premières lignes.

Alors que :

In [33]:
df.loc[:, ["country", "category"]]

      country     category
0     Germany  Electronics
1       Italy       Sports
2       Italy         Home
3     Belgium         Home
4       Italy     Clothing
...       ...          ...
5010   France        Books
5011  Germany       Sports
5012  Germany     clothing
5013    Spain  Electronics
5014  Germany     Clothing

[5015 rows x 2 columns]

signifie :

> toutes les lignes et les colonnes dont le nom est `country` et `category`.

# 20. Filtrer avec une condition

Supposons que nous voulions uniquement les commandes dont la quantité est supérieure à 5.

Commençons par construire la condition :

In [34]:
df["quantity"] > 5

0        True
1       False
2       False
3       False
4       False
        ...
5010    False
5011    False
5012    False
5013    False
5014    False
Name: quantity, Length: 5015, dtype: bool

Le résultat est une série de booléens :

```text
True
False
False
True
...
```

# 21. Utiliser la condition comme filtre

In [35]:
df[df["quantity"] > 5]

,order_id,customer_id,order_date,country,category,quantity,unit_price,discount,payment_method,customer_rating,amount
0,ORD-004875,CUST-00286,2024-11-12 09:40:00,Germany,Electronics,8,847.65,0.20,Apple Pay,3.0,6781.20
22,ORD-003241,CUST-00314,2025-02-22 11:43:00,France,Clothing,6,53.20,0.20,PayPal,2.0,319.20
36,ORD-001895,CUST-00202,2025-05-24 01:36:00,France,Electronics,7,415.58,0.00,Bank Transfer,5.0,2909.06
47,ORD-004206,CUST-01211,2025-07-30 06:54:00,France,Books,6,80.00,0.30,PayPal,5.0,480.00
77,ORD-000486,CUST-00349,2024-05-22 07:38:00,Spain,Books,6,51.64,0.00,Credit Card,5.0,309.84
...,...,...,...,...,...,...,...,...,...,...,...
4957,ORD-001022,CUST-00109,2024-09-16 18:38:00,Netherlands,Books,8,30.60,0.05,Credit Card,4.0,244.80
4967,ORD-001479,CUST-00346,2024-11-03 14:03:00,Italy,Books,8,66.24,0.15,Credit Card,3.0,529.92
4986,ORD-003006,CUST-00557,2024-02-09 06:00:00,Spain,Books,6,31.00,0.00,Credit Card,3.0,186.00
4987,ORD-002735,CUST-00672,2025-09-10 02:59:00,Italy,Sports,7,400.00,0.20,Bank Transfer,4.0,2800.00
5005,ORD-001686,CUST-00781,2024-08-23 17:35:00,Belgium,Books,7,70.44,0.05,Credit Card,4.0,493.08

Nous avons créé un **masque booléen**.

Conceptuellement :

```text
DataFrame
    │
    ↓
condition
    │
    ↓
True / False
    │
    ↓
lignes conservées
```

C'est l'un des mécanismes fondamentaux de Pandas.

# 22. Filtrer sur une variable numérique

Commandes supérieures à 100 € :

In [36]:
df[df["amount"] > 100]

,order_id,customer_id,order_date,country,category,quantity,unit_price,discount,payment_method,customer_rating,amount
0,ORD-004875,CUST-00286,2024-11-12 09:40:00,Germany,Electronics,8,847.65,0.20,Apple Pay,3.0,6781.20
1,ORD-001026,CUST-00084,2025-09-11 12:22:00,Italy,Sports,2,166.25,0.00,Bank Transfer,3.0,332.50
2,ORD-003546,CUST-00947,2025-04-26 08:58:00,Italy,Home,3,500.00,0.10,Credit Card,3.0,1500.00
3,ORD-003822,CUST-00017,2024-06-01 14:55:00,Belgium,Home,2,346.55,0.10,Credit Card,5.0,693.10
4,ORD-004395,CUST-00764,2024-01-26 12:23:00,Italy,Clothing,2,228.08,0.00,Bank Transfer,5.0,456.16
...,...,...,...,...,...,...,...,...,...,...,...
5007,ORD-002920,CUST-00568,2025-05-10 23:06:00,Spain,Clothing,1,173.59,0.20,Credit Card,2.0,173.59
5011,ORD-000467,CUST-00249,2025-02-19 22:32:00,Germany,Sports,3,229.10,0.05,Credit Card,4.0,687.30
5012,ORD-003093,CUST-01079,2024-07-16 17:48:00,Germany,clothing,1,178.44,0.00,Bank Transfer,5.0,178.44
5013,ORD-003773,CUST-00792,2025-07-08 05:15:00,Spain,Electronics,2,1200.00,0.00,Credit Card,5.0,2400.00
5014,ORD-000861,CUST-01453,2024-01-10 05:41:00,Germany,Clothing,1,183.05,0.05,Bank Transfer,5.0,183.05

Commandes dont la quantité est égale à 1 :

In [37]:
df[df["quantity"] == 1]

,order_id,customer_id,order_date,country,category,quantity,unit_price,discount,payment_method,customer_rating,amount
6,ORD-002418,CUST-00391,2024-08-20 12:14:00,France,Books,1,35.68,0.00,Bank Transfer,5.0,35.68
7,ORD-001096,CUST-00121,2024-01-25 01:22:00,Italy,Clothing,1,245.59,0.05,Credit Card,4.0,245.59
10,ORD-002375,CUST-01049,2025-10-05 09:16:00,France,Clothing,1,216.20,0.00,Credit Card,4.0,216.20
12,ORD-000801,CUST-00019,2025-06-28 21:05:00,France,Books,1,66.92,0.00,Bank Transfer,NaN,66.92
16,ORD-003650,CUST-01107,2024-01-11 05:46:00,Germany,Electronics,1,607.94,0.20,Credit Card,4.0,607.94
...,...,...,...,...,...,...,...,...,...,...,...
5007,ORD-002920,CUST-00568,2025-05-10 23:06:00,Spain,Clothing,1,173.59,0.20,Credit Card,2.0,173.59
5009,ORD-003445,CUST-01377,2025-08-07 18:28:00,Germany,Books,1,80.00,0.00,Bank Transfer,NaN,80.00
5010,ORD-004427,CUST-00386,2025-11-19 03:36:00,France,Books,1,37.46,0.15,PayPal,5.0,37.46
5012,ORD-003093,CUST-01079,2024-07-16 17:48:00,Germany,clothing,1,178.44,0.00,Bank Transfer,5.0,178.44
5014,ORD-000861,CUST-01453,2024-01-10 05:41:00,Germany,Clothing,1,183.05,0.05,Bank Transfer,5.0,183.05

Commandes dont la quantité est différente de 1 :

In [38]:
df[df["quantity"] != 1]

,order_id,customer_id,order_date,country,category,quantity,unit_price,discount,payment_method,customer_rating,amount
0,ORD-004875,CUST-00286,2024-11-12 09:40:00,Germany,Electronics,8,847.65,0.20,Apple Pay,3.0,6781.20
1,ORD-001026,CUST-00084,2025-09-11 12:22:00,Italy,Sports,2,166.25,0.00,Bank Transfer,3.0,332.50
2,ORD-003546,CUST-00947,2025-04-26 08:58:00,Italy,Home,3,500.00,0.10,Credit Card,3.0,1500.00
3,ORD-003822,CUST-00017,2024-06-01 14:55:00,Belgium,Home,2,346.55,0.10,Credit Card,5.0,693.10
4,ORD-004395,CUST-00764,2024-01-26 12:23:00,Italy,Clothing,2,228.08,0.00,Bank Transfer,5.0,456.16
...,...,...,...,...,...,...,...,...,...,...,...
5005,ORD-001686,CUST-00781,2024-08-23 17:35:00,Belgium,Books,7,70.44,0.05,Credit Card,4.0,493.08
5006,ORD-000131,CUST-00849,2024-05-10 03:48:00,Belgium,Books,2,80.00,0.10,Credit Card,5.0,160.00
5008,ORD-003172,CUST-01409,2024-11-23 09:54:00,France,Books,2,33.39,0.15,Credit Card,5.0,66.78
5011,ORD-000467,CUST-00249,2025-02-19 22:32:00,Germany,Sports,3,229.10,0.05,Credit Card,4.0,687.30
5013,ORD-003773,CUST-00792,2025-07-08 05:15:00,Spain,Electronics,2,1200.00,0.00,Credit Card,5.0,2400.00

# 23. Filtrer sur du texte

Toutes les commandes provenant de France :

In [39]:
df[df["country"] == "France"]

,order_id,customer_id,order_date,country,category,quantity,unit_price,discount,payment_method,customer_rating,amount
6,ORD-002418,CUST-00391,2024-08-20 12:14:00,France,Books,1,35.68,0.00,Bank Transfer,5.0,35.68
10,ORD-002375,CUST-01049,2025-10-05 09:16:00,France,Clothing,1,216.20,0.00,Credit Card,4.0,216.20
12,ORD-000801,CUST-00019,2025-06-28 21:05:00,France,Books,1,66.92,0.00,Bank Transfer,NaN,66.92
14,ORD-001457,CUST-01477,2025-07-20 23:19:00,France,Books,3,51.87,0.20,PayPal,5.0,155.61
19,ORD-002813,CUST-00297,2025-01-18 15:21:00,France,Clothing,3,131.81,0.30,Credit Card,4.0,395.43
...,...,...,...,...,...,...,...,...,...,...,...
4996,ORD-002905,CUST-00978,2025-08-04 05:10:00,France,Books,2,39.95,0.00,Apple Pay,5.0,79.90
4998,ORD-004118,CUST-00197,2025-06-16 00:46:00,France,Clothing,3,95.36,0.00,Bank Transfer,3.0,286.08
5001,ORD-001185,CUST-00631,2025-01-06 09:56:00,France,Electronics,2,385.28,0.10,PayPal,5.0,770.56
5008,ORD-003172,CUST-01409,2024-11-23 09:54:00,France,Books,2,33.39,0.15,Credit Card,5.0,66.78
5010,ORD-004427,CUST-00386,2025-11-19 03:36:00,France,Books,1,37.46,0.15,PayPal,5.0,37.46

Toutes les commandes provenant d'Allemagne :

In [40]:
df[df["country"] == "Germany"]

,order_id,customer_id,order_date,country,category,quantity,unit_price,discount,payment_method,customer_rating,amount
0,ORD-004875,CUST-00286,2024-11-12 09:40:00,Germany,Electronics,8,847.65,0.20,Apple Pay,3.0,6781.20
8,ORD-004460,CUST-00981,2025-07-05 11:39:00,Germany,Clothing,3,163.35,0.15,Credit Card,3.0,490.05
15,ORD-001392,CUST-00795,2025-01-04 10:54:00,Germany,Sports,4,340.39,0.10,PayPal,NaN,1361.56
16,ORD-003650,CUST-01107,2024-01-11 05:46:00,Germany,Electronics,1,607.94,0.20,Credit Card,4.0,607.94
17,ORD-003200,CUST-00398,2025-10-25 09:38:00,Germany,Electronics,1,241.71,0.00,PayPal,3.0,241.71
...,...,...,...,...,...,...,...,...,...,...,...
5003,ORD-002392,CUST-00289,2024-12-25 02:14:00,Germany,Clothing,5,104.52,0.00,Bank Transfer,4.0,522.60
5009,ORD-003445,CUST-01377,2025-08-07 18:28:00,Germany,Books,1,80.00,0.00,Bank Transfer,NaN,80.00
5011,ORD-000467,CUST-00249,2025-02-19 22:32:00,Germany,Sports,3,229.10,0.05,Credit Card,4.0,687.30
5012,ORD-003093,CUST-01079,2024-07-16 17:48:00,Germany,clothing,1,178.44,0.00,Bank Transfer,5.0,178.44
5014,ORD-000861,CUST-01453,2024-01-10 05:41:00,Germany,Clothing,1,183.05,0.05,Bank Transfer,5.0,183.05

# 24. Plusieurs conditions

Supposons que nous voulions :

> les commandes françaises de plus de 100 €.

In [41]:
df[
    (df["country"] == "France")
    & (df["amount"] > 100)
]

,order_id,customer_id,order_date,country,category,quantity,unit_price,discount,payment_method,customer_rating,amount
10,ORD-002375,CUST-01049,2025-10-05 09:16:00,France,Clothing,1,216.20,0.0,Credit Card,4.0,216.20
14,ORD-001457,CUST-01477,2025-07-20 23:19:00,France,Books,3,51.87,0.2,PayPal,5.0,155.61
19,ORD-002813,CUST-00297,2025-01-18 15:21:00,France,Clothing,3,131.81,0.3,Credit Card,4.0,395.43
22,ORD-003241,CUST-00314,2025-02-22 11:43:00,France,Clothing,6,53.20,0.2,PayPal,2.0,319.20
28,ORD-003014,CUST-01105,2025-02-08 12:59:00,France,Electronics,3,613.81,0.2,Credit Card,3.0,1841.43
...,...,...,...,...,...,...,...,...,...,...,...
4990,ORD-000976,CUST-00339,2025-05-22 23:16:00,France,Home,4,302.13,0.0,Bank Transfer,4.0,1208.52
4991,ORD-002748,CUST-01214,2025-08-14 08:16:00,France,Books,2,80.00,0.0,Credit Card,5.0,160.00
4994,ORD-001083,CUST-01438,2024-10-22 09:25:00,France,Home,1,338.49,0.0,Credit Card,2.0,338.49
4998,ORD-004118,CUST-00197,2025-06-16 00:46:00,France,Clothing,3,95.36,0.0,Bank Transfer,3.0,286.08
5001,ORD-001185,CUST-00631,2025-01-06 09:56:00,France,Electronics,2,385.28,0.1,PayPal,5.0,770.56

## Les opérateurs importants

Avec Pandas, on utilise :

| Python logique | Pandas |
| -------------- | ------ |
| `and`          | `&`    |
| `or`           | `\|`   |
| `not`          | `~`    |

Et il faut généralement entourer chaque condition de parenthèses.

# 25. `OR`

Commandes provenant de France **ou** d'Allemagne :

In [42]:
df[
    (df["country"] == "France")
    | (df["country"] == "Germany")
]

,order_id,customer_id,order_date,country,category,quantity,unit_price,discount,payment_method,customer_rating,amount
0,ORD-004875,CUST-00286,2024-11-12 09:40:00,Germany,Electronics,8,847.65,0.20,Apple Pay,3.0,6781.20
6,ORD-002418,CUST-00391,2024-08-20 12:14:00,France,Books,1,35.68,0.00,Bank Transfer,5.0,35.68
8,ORD-004460,CUST-00981,2025-07-05 11:39:00,Germany,Clothing,3,163.35,0.15,Credit Card,3.0,490.05
10,ORD-002375,CUST-01049,2025-10-05 09:16:00,France,Clothing,1,216.20,0.00,Credit Card,4.0,216.20
12,ORD-000801,CUST-00019,2025-06-28 21:05:00,France,Books,1,66.92,0.00,Bank Transfer,NaN,66.92
...,...,...,...,...,...,...,...,...,...,...,...
5009,ORD-003445,CUST-01377,2025-08-07 18:28:00,Germany,Books,1,80.00,0.00,Bank Transfer,NaN,80.00
5010,ORD-004427,CUST-00386,2025-11-19 03:36:00,France,Books,1,37.46,0.15,PayPal,5.0,37.46
5011,ORD-000467,CUST-00249,2025-02-19 22:32:00,Germany,Sports,3,229.10,0.05,Credit Card,4.0,687.30
5012,ORD-003093,CUST-01079,2024-07-16 17:48:00,Germany,clothing,1,178.44,0.00,Bank Transfer,5.0,178.44
5014,ORD-000861,CUST-01453,2024-01-10 05:41:00,Germany,Clothing,1,183.05,0.05,Bank Transfer,5.0,183.05

# 26. `isin()`

Lorsque nous voulons tester plusieurs valeurs, `isin()` est souvent plus lisible.

In [43]:
df[
    df["country"].isin(
        ["France", "Germany", "Spain"]
    )
]

,order_id,customer_id,order_date,country,category,quantity,unit_price,discount,payment_method,customer_rating,amount
0,ORD-004875,CUST-00286,2024-11-12 09:40:00,Germany,Electronics,8,847.65,0.20,Apple Pay,3.0,6781.20
6,ORD-002418,CUST-00391,2024-08-20 12:14:00,France,Books,1,35.68,0.00,Bank Transfer,5.0,35.68
8,ORD-004460,CUST-00981,2025-07-05 11:39:00,Germany,Clothing,3,163.35,0.15,Credit Card,3.0,490.05
9,ORD-000706,CUST-00848,2025-11-07 12:37:00,Spain,Electronics,4,679.09,0.00,Apple Pay,5.0,2716.36
10,ORD-002375,CUST-01049,2025-10-05 09:16:00,France,Clothing,1,216.20,0.00,Credit Card,4.0,216.20
...,...,...,...,...,...,...,...,...,...,...,...
5010,ORD-004427,CUST-00386,2025-11-19 03:36:00,France,Books,1,37.46,0.15,PayPal,5.0,37.46
5011,ORD-000467,CUST-00249,2025-02-19 22:32:00,Germany,Sports,3,229.10,0.05,Credit Card,4.0,687.30
5012,ORD-003093,CUST-01079,2024-07-16 17:48:00,Germany,clothing,1,178.44,0.00,Bank Transfer,5.0,178.44
5013,ORD-003773,CUST-00792,2025-07-08 05:15:00,Spain,Electronics,2,1200.00,0.00,Credit Card,5.0,2400.00
5014,ORD-000861,CUST-01453,2024-01-10 05:41:00,Germany,Clothing,1,183.05,0.05,Bank Transfer,5.0,183.05

Cela signifie :

> conserver les lignes dont le pays appartient à cette liste.

# 27. `between()`

Pour sélectionner une plage numérique :

In [44]:
df[
    df["amount"].between(50, 100)
]

,order_id,customer_id,order_date,country,category,quantity,unit_price,discount,payment_method,customer_rating,amount
12,ORD-000801,CUST-00019,2025-06-28 21:05:00,France,Books,1,66.92,0.00,Bank Transfer,NaN,66.92
23,ORD-004102,CUST-01482,2025-11-24 20:58:00,France,Clothing,1,87.46,0.10,Apple Pay,5.0,87.46
24,ORD-000627,CUST-00508,2025-03-10 14:18:00,France,Clothing,1,85.31,0.10,Apple Pay,4.0,85.31
25,ORD-001966,CUST-01113,2024-09-14 17:32:00,France,Books,1,80.00,0.10,Bank Transfer,5.0,80.00
34,ORD-000684,CUST-01439,2025-01-04 23:25:00,Belgium,Books,4,23.35,0.00,Bank Transfer,5.0,93.40
...,...,...,...,...,...,...,...,...,...,...,...
4976,ORD-002436,CUST-00847,2024-09-19 22:16:00,Germany,Books,1,56.67,0.00,Credit Card,5.0,56.67
4977,ORD-002889,CUST-00223,2024-03-29 06:47:00,Belgium,Books,4,14.76,0.00,PayPal,4.0,59.04
4996,ORD-002905,CUST-00978,2025-08-04 05:10:00,France,Books,2,39.95,0.00,Apple Pay,5.0,79.90
5008,ORD-003172,CUST-01409,2024-11-23 09:54:00,France,Books,2,33.39,0.15,Credit Card,5.0,66.78
5009,ORD-003445,CUST-01377,2025-08-07 18:28:00,Germany,Books,1,80.00,0.00,Bank Transfer,NaN,80.00

Cela sélectionne les commandes dont le montant est compris entre 50 et 100.

# 28. `query()`

Pandas fournit également une syntaxe plus proche d'une requête.

In [45]:
df.query("amount > 100")

,order_id,customer_id,order_date,country,category,quantity,unit_price,discount,payment_method,customer_rating,amount
0,ORD-004875,CUST-00286,2024-11-12 09:40:00,Germany,Electronics,8,847.65,0.20,Apple Pay,3.0,6781.20
1,ORD-001026,CUST-00084,2025-09-11 12:22:00,Italy,Sports,2,166.25,0.00,Bank Transfer,3.0,332.50
2,ORD-003546,CUST-00947,2025-04-26 08:58:00,Italy,Home,3,500.00,0.10,Credit Card,3.0,1500.00
3,ORD-003822,CUST-00017,2024-06-01 14:55:00,Belgium,Home,2,346.55,0.10,Credit Card,5.0,693.10
4,ORD-004395,CUST-00764,2024-01-26 12:23:00,Italy,Clothing,2,228.08,0.00,Bank Transfer,5.0,456.16
...,...,...,...,...,...,...,...,...,...,...,...
5007,ORD-002920,CUST-00568,2025-05-10 23:06:00,Spain,Clothing,1,173.59,0.20,Credit Card,2.0,173.59
5011,ORD-000467,CUST-00249,2025-02-19 22:32:00,Germany,Sports,3,229.10,0.05,Credit Card,4.0,687.30
5012,ORD-003093,CUST-01079,2024-07-16 17:48:00,Germany,clothing,1,178.44,0.00,Bank Transfer,5.0,178.44
5013,ORD-003773,CUST-00792,2025-07-08 05:15:00,Spain,Electronics,2,1200.00,0.00,Credit Card,5.0,2400.00
5014,ORD-000861,CUST-01453,2024-01-10 05:41:00,Germany,Clothing,1,183.05,0.05,Bank Transfer,5.0,183.05

Plusieurs conditions :

In [46]:
df.query(
    "amount > 100 and quantity >= 2"
)

,order_id,customer_id,order_date,country,category,quantity,unit_price,discount,payment_method,customer_rating,amount
0,ORD-004875,CUST-00286,2024-11-12 09:40:00,Germany,Electronics,8,847.65,0.20,Apple Pay,3.0,6781.20
1,ORD-001026,CUST-00084,2025-09-11 12:22:00,Italy,Sports,2,166.25,0.00,Bank Transfer,3.0,332.50
2,ORD-003546,CUST-00947,2025-04-26 08:58:00,Italy,Home,3,500.00,0.10,Credit Card,3.0,1500.00
3,ORD-003822,CUST-00017,2024-06-01 14:55:00,Belgium,Home,2,346.55,0.10,Credit Card,5.0,693.10
4,ORD-004395,CUST-00764,2024-01-26 12:23:00,Italy,Clothing,2,228.08,0.00,Bank Transfer,5.0,456.16
...,...,...,...,...,...,...,...,...,...,...,...
5004,ORD-000770,CUST-00565,2024-05-28 18:19:00,Italy,Books,4,34.00,0.00,PayPal,4.0,136.00
5005,ORD-001686,CUST-00781,2024-08-23 17:35:00,Belgium,Books,7,70.44,0.05,Credit Card,4.0,493.08
5006,ORD-000131,CUST-00849,2024-05-10 03:48:00,Belgium,Books,2,80.00,0.10,Credit Card,5.0,160.00
5011,ORD-000467,CUST-00249,2025-02-19 22:32:00,Germany,Sports,3,229.10,0.05,Credit Card,4.0,687.30
5013,ORD-003773,CUST-00792,2025-07-08 05:15:00,Spain,Electronics,2,1200.00,0.00,Credit Card,5.0,2400.00

# 29. Comparaison des approches

Les trois approches suivantes peuvent être utilisées :

In [47]:
df[df["amount"] > 100]

,order_id,customer_id,order_date,country,category,quantity,unit_price,discount,payment_method,customer_rating,amount
0,ORD-004875,CUST-00286,2024-11-12 09:40:00,Germany,Electronics,8,847.65,0.20,Apple Pay,3.0,6781.20
1,ORD-001026,CUST-00084,2025-09-11 12:22:00,Italy,Sports,2,166.25,0.00,Bank Transfer,3.0,332.50
2,ORD-003546,CUST-00947,2025-04-26 08:58:00,Italy,Home,3,500.00,0.10,Credit Card,3.0,1500.00
3,ORD-003822,CUST-00017,2024-06-01 14:55:00,Belgium,Home,2,346.55,0.10,Credit Card,5.0,693.10
4,ORD-004395,CUST-00764,2024-01-26 12:23:00,Italy,Clothing,2,228.08,0.00,Bank Transfer,5.0,456.16
...,...,...,...,...,...,...,...,...,...,...,...
5007,ORD-002920,CUST-00568,2025-05-10 23:06:00,Spain,Clothing,1,173.59,0.20,Credit Card,2.0,173.59
5011,ORD-000467,CUST-00249,2025-02-19 22:32:00,Germany,Sports,3,229.10,0.05,Credit Card,4.0,687.30
5012,ORD-003093,CUST-01079,2024-07-16 17:48:00,Germany,clothing,1,178.44,0.00,Bank Transfer,5.0,178.44
5013,ORD-003773,CUST-00792,2025-07-08 05:15:00,Spain,Electronics,2,1200.00,0.00,Credit Card,5.0,2400.00
5014,ORD-000861,CUST-01453,2024-01-10 05:41:00,Germany,Clothing,1,183.05,0.05,Bank Transfer,5.0,183.05

In [48]:
df[df["amount"].between(100, 1000)]

,order_id,customer_id,order_date,country,category,quantity,unit_price,discount,payment_method,customer_rating,amount
1,ORD-001026,CUST-00084,2025-09-11 12:22:00,Italy,Sports,2,166.25,0.00,Bank Transfer,3.0,332.50
3,ORD-003822,CUST-00017,2024-06-01 14:55:00,Belgium,Home,2,346.55,0.10,Credit Card,5.0,693.10
4,ORD-004395,CUST-00764,2024-01-26 12:23:00,Italy,Clothing,2,228.08,0.00,Bank Transfer,5.0,456.16
7,ORD-001096,CUST-00121,2024-01-25 01:22:00,Italy,Clothing,1,245.59,0.05,Credit Card,4.0,245.59
8,ORD-004460,CUST-00981,2025-07-05 11:39:00,Germany,Clothing,3,163.35,0.15,Credit Card,3.0,490.05
...,...,...,...,...,...,...,...,...,...,...,...
5006,ORD-000131,CUST-00849,2024-05-10 03:48:00,Belgium,Books,2,80.00,0.10,Credit Card,5.0,160.00
5007,ORD-002920,CUST-00568,2025-05-10 23:06:00,Spain,Clothing,1,173.59,0.20,Credit Card,2.0,173.59
5011,ORD-000467,CUST-00249,2025-02-19 22:32:00,Germany,Sports,3,229.10,0.05,Credit Card,4.0,687.30
5012,ORD-003093,CUST-01079,2024-07-16 17:48:00,Germany,clothing,1,178.44,0.00,Bank Transfer,5.0,178.44
5014,ORD-000861,CUST-01453,2024-01-10 05:41:00,Germany,Clothing,1,183.05,0.05,Bank Transfer,5.0,183.05

In [49]:
df.query("amount > 100")

,order_id,customer_id,order_date,country,category,quantity,unit_price,discount,payment_method,customer_rating,amount
0,ORD-004875,CUST-00286,2024-11-12 09:40:00,Germany,Electronics,8,847.65,0.20,Apple Pay,3.0,6781.20
1,ORD-001026,CUST-00084,2025-09-11 12:22:00,Italy,Sports,2,166.25,0.00,Bank Transfer,3.0,332.50
2,ORD-003546,CUST-00947,2025-04-26 08:58:00,Italy,Home,3,500.00,0.10,Credit Card,3.0,1500.00
3,ORD-003822,CUST-00017,2024-06-01 14:55:00,Belgium,Home,2,346.55,0.10,Credit Card,5.0,693.10
4,ORD-004395,CUST-00764,2024-01-26 12:23:00,Italy,Clothing,2,228.08,0.00,Bank Transfer,5.0,456.16
...,...,...,...,...,...,...,...,...,...,...,...
5007,ORD-002920,CUST-00568,2025-05-10 23:06:00,Spain,Clothing,1,173.59,0.20,Credit Card,2.0,173.59
5011,ORD-000467,CUST-00249,2025-02-19 22:32:00,Germany,Sports,3,229.10,0.05,Credit Card,4.0,687.30
5012,ORD-003093,CUST-01079,2024-07-16 17:48:00,Germany,clothing,1,178.44,0.00,Bank Transfer,5.0,178.44
5013,ORD-003773,CUST-00792,2025-07-08 05:15:00,Spain,Electronics,2,1200.00,0.00,Credit Card,5.0,2400.00
5014,ORD-000861,CUST-01453,2024-01-10 05:41:00,Germany,Clothing,1,183.05,0.05,Bank Transfer,5.0,183.05

Il ne s'agit pas de choisir une syntaxe "magique".

L'objectif est de savoir **quelle expression est la plus claire dans le contexte**.

# 30. Explorer une variable catégorielle

Imaginons que nous voulions connaître les pays présents dans notre dataset.

In [50]:
df["country"].unique()

array(['Germany', 'Italy', 'Belgium', 'Netherlands', 'France', 'Spain',
       ' Netherlands', nan, ' Belgium', ' Spain', ' Italy', ' France',
       ' Germany'], dtype=object)

## Combien de pays différents ?

In [51]:
df["country"].nunique()

12

## Combien de commandes par pays ?

In [52]:
df["country"].value_counts()

country
France          1741
Germany          970
Spain            766
Italy            625
Belgium          490
Netherlands      388
 Netherlands       4
 Spain             3
 France            3
 Belgium           2
 Italy             2
 Germany           1
Name: count, dtype: int64

# 31. `value_counts()` : une commande essentielle

Pour une variable catégorielle :

In [53]:
df["category"].value_counts()

category
Electronics    1244
Clothing       1185
Home           1000
Books           773
Sports          768
clothing          5
electronics       4
home              3
sports            2
books             1
Name: count, dtype: int64

Nous obtenons par exemple :

```text
Electronics    3210
Clothing       2870
Home           2340
Books          1580
```

Cela permet immédiatement de voir la distribution des catégories.

# 32. Obtenir des proportions

On peut demander les fréquences relatives :

In [54]:
df["category"].value_counts(
    normalize=True
)

category
Electronics    0.249549
Clothing       0.237713
Home           0.200602
Books          0.155065
Sports         0.154062
clothing       0.001003
electronics    0.000802
home           0.000602
sports         0.000401
books          0.000201
Name: proportion, dtype: float64

Par exemple :

```text
Electronics    0.321
Clothing       0.287
Home           0.234
Books          0.158
```

Soit :

```text
32.1 %
28.7 %
23.4 %
15.8 %
```

# 33. Explorer une variable numérique

Pour une variable numérique :

In [55]:
df["amount"].describe()

count      5015.000000
mean        943.374802
std        4170.569059
min          11.420000
25%         179.950000
50%         419.340000
75%         995.660000
max      218816.150000
Name: amount, dtype: float64

On obtient notamment :

```text
count
mean
std
min
25%
50%
75%
max
```

# 34. Comprendre les quartiles

Supposons :

```text
25%    = 32 €
50%    = 61 €
75%    = 120 €
```

La médiane est :

```text
50% → 61 €
```

Cela signifie que 50 % des observations sont inférieures ou égales à 61 €.

Et 75 % sont inférieures ou égales à 120 €.

# 35. `describe()` sur tout le DataFrame

In [56]:
df.describe()

          quantity    unit_price     discount  customer_rating         amount
count  5015.000000   5015.000000  5015.000000      4615.000000    5015.000000
mean      2.761117    322.170449     0.064148         3.915276     943.374802
std       4.957655    538.134329     0.074894         1.162172    4170.569059
min       1.000000      8.000000     0.000000         1.000000      11.420000
25%       1.000000     98.325000     0.000000         3.000000     179.950000
50%       2.000000    210.230000     0.050000         4.000000     419.340000
75%       4.000000    400.000000     0.100000         5.000000     995.660000
max     185.000000  14139.060000     0.300000         5.000000  218816.150000

Pandas sélectionne automatiquement les variables numériques.

# 36. Statistiques catégorielles

Pour obtenir également des informations sur les colonnes non numériques :

In [57]:
df.describe(include="all")

,order_id,customer_id,order_date,country,category,quantity,unit_price,discount,payment_method,customer_rating,amount
count,5015,5015,5015,4995,4985,5015.000000,5015.000000,5015.000000,5015,4615.000000,5015.000000
unique,5000,1438,4989,12,10,NaN,NaN,NaN,4,NaN,NaN
top,ORD-000795,CUST-00435,2024-02-22 11:38:00,France,Electronics,NaN,NaN,NaN,Credit Card,NaN,NaN
freq,2,10,2,1741,1244,NaN,NaN,NaN,2444,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,2.761117,322.170449,0.064148,NaN,3.915276,943.374802
std,NaN,NaN,NaN,NaN,NaN,4.957655,538.134329,0.074894,NaN,1.162172,4170.569059
min,NaN,NaN,NaN,NaN,NaN,1.000000,8.000000,0.000000,NaN,1.000000,11.420000
25%,NaN,NaN,NaN,NaN,NaN,1.000000,98.325000,0.000000,NaN,3.000000,179.950000
50%,NaN,NaN,NaN,NaN,NaN,2.000000,210.230000,0.050000,NaN,4.000000,419.340000
75%,NaN,NaN,NaN,NaN,NaN,4.000000,400.000000,0.100000,NaN,5.000000,995.660000
max,NaN,NaN,NaN,NaN,NaN,185.000000,14139.060000,0.300000,NaN,5.000000,218816.150000

Cette commande peut être très utile lors d'une première exploration.

# 37. Compter les valeurs manquantes

Une question essentielle :

> **Combien de valeurs sont absentes ?**

In [58]:
df.isna().sum()

order_id             0
customer_id          0
order_date           0
country             20
category            30
quantity             0
unit_price           0
discount             0
payment_method       0
customer_rating    400
amount               0
dtype: int64

# 38. Calculer le taux de valeurs manquantes

In [59]:
df.isna().mean() * 100

order_id           0.000000
customer_id        0.000000
order_date         0.000000
country            0.398804
category           0.598205
quantity           0.000000
unit_price         0.000000
discount           0.000000
payment_method     0.000000
customer_rating    7.976072
amount             0.000000
dtype: float64

Nous obtenons alors un pourcentage par colonne.

Par exemple :

```text
order_id            0.0 %
customer_id         0.0 %
order_date          0.0 %
country             0.2 %
category            1.4 %
customer_rating     8.7 %
```

# 39. Pourquoi les valeurs manquantes sont-elles importantes ?

Supposons :

```text
customer_rating
----------------
5
4
3
NaN
5
NaN
```

Les `NaN` ne signifient pas nécessairement :

> "Le client a donné une note de 0."

Ils signifient :

> "Nous n'avons pas de valeur."

Cette distinction est fondamentale en Data Science.

# 40. Vérifier les doublons

Nous pouvons également rechercher les lignes dupliquées :

In [60]:
df.duplicated().sum()

np.int64(15)

# 41. Première exploration statistique

Nous pouvons maintenant commencer à poser des questions métier.

### Quel est le montant moyen d'une commande ?

In [61]:
df["amount"].mean()

np.float64(943.3748015952145)

### Quel est le montant médian ?

In [62]:
df["amount"].median()

419.34

### Quel est le montant maximum ?

In [63]:
df["amount"].max()

218816.15

### Quelle est la quantité moyenne ?

In [64]:
df["quantity"].mean()

np.float64(2.7611166500498503)

# 42. Comparer moyenne et médiane

Calculons :

In [65]:
mean_amount = df["amount"].mean()
median_amount = df["amount"].median()

print("Moyenne :", mean_amount)
print("Médiane :", median_amount)

Moyenne : 943.3748015952145
Médiane : 419.34

## 🧠 Question

Que peut-on déduire si :

```text
moyenne  = 142 €
médiane  = 72 €
```

La moyenne est fortement supérieure à la médiane.

Cela peut être un indice de la présence de **valeurs élevées** qui tirent la moyenne vers le haut.

# 43. Explorer les valeurs extrêmes

Minimum :

In [66]:
df["amount"].min()

11.42

Maximum :

In [67]:
df["amount"].max()

218816.15

Les quantiles :

In [68]:
df["amount"].quantile(
    [0.01, 0.25, 0.50, 0.75, 0.99]
)

0.01      25.3732
0.25     179.9500
0.50     419.3400
0.75     995.6600
0.99    5602.7412
Name: amount, dtype: float64

# 44. Identifier les commandes les plus importantes

Les 10 commandes les plus élevées :

In [69]:
df.nlargest(
    10,
    "amount"
)

,order_id,customer_id,order_date,country,category,quantity,unit_price,discount,payment_method,customer_rating,amount
3388,ORD-001711,CUST-00514,2024-07-26 12:58:00,Spain,Electronics,185,1182.79,0.15,PayPal,5.0,218816.15
1584,ORD-003530,CUST-00181,2024-10-28 20:38:00,Spain,Electronics,138,938.98,0.10,Credit Card,NaN,129579.24
2009,ORD-003897,CUST-00799,2025-02-07 19:12:00,Germany,Books,7,11854.12,0.10,PayPal,3.0,82978.84
2943,ORD-001005,CUST-00193,2024-02-18 11:47:00,Italy,Electronics,122,446.69,0.00,Credit Card,5.0,54496.18
4764,ORD-001528,CUST-00208,2024-12-24 19:01:00,Italy,Electronics,4,12452.67,0.10,PayPal,3.0,49810.68
4938,ORD-004888,CUST-00810,2025-08-03 04:13:00,Belgium,Home,89,500.00,0.15,PayPal,5.0,44500.00
4921,ORD-003100,CUST-00410,2025-06-16 07:36:00,Germany,Clothing,2,14139.06,0.05,PayPal,5.0,28278.12
817,ORD-000176,CUST-00693,2024-03-14 14:18:00,Spain,Sports,5,5559.82,0.00,Credit Card,5.0,27799.10
226,ORD-000374,CUST-00561,2024-07-16 05:35:00,France,Clothing,2,13785.05,0.00,PayPal,NaN,27570.10
4922,ORD-002279,CUST-00554,2025-10-07 18:47:00,Germany,Clothing,90,243.44,0.00,Credit Card,4.0,21909.60

Les 10 plus petites :

In [70]:
df.nsmallest(
    10,
    "amount"
)

,order_id,customer_id,order_date,country,category,quantity,unit_price,discount,payment_method,customer_rating,amount
359,ORD-000430,CUST-01074,2024-02-16 06:49:00,Spain,Books,1,11.42,0.10,PayPal,5.0,11.42
4155,ORD-002675,CUST-01397,2024-01-08 03:46:00,France,Books,1,11.49,0.00,Credit Card,3.0,11.49
4535,ORD-003637,CUST-00811,2025-03-15 20:48:00,France,Books,1,12.54,0.00,Bank Transfer,2.0,12.54
1336,ORD-001425,CUST-00384,2025-09-15 08:03:00,France,Books,1,12.74,0.00,Credit Card,5.0,12.74
2726,ORD-000042,CUST-01138,2025-05-10 02:44:00,Germany,Books,1,13.22,0.05,Bank Transfer,1.0,13.22
627,ORD-002723,CUST-00171,2024-06-24 04:20:00,France,Books,1,13.47,0.00,Credit Card,NaN,13.47
4537,ORD-004492,CUST-00296,2024-09-20 05:40:00,Italy,Books,1,14.37,0.00,PayPal,5.0,14.37
1082,ORD-003323,CUST-01180,2024-05-03 18:22:00,Italy,Books,1,15.36,0.05,Credit Card,4.0,15.36
4914,ORD-000805,CUST-01108,2025-04-28 07:14:00,Spain,Books,1,15.37,0.10,PayPal,1.0,15.37
4005,ORD-004406,CUST-01343,2024-11-24 07:48:00,Belgium,Books,1,15.49,0.00,PayPal,5.0,15.49

# 45. Une première question métier

Imaginons que le directeur commercial demande :

> "Quelles sont les 10 commandes qui représentent les plus gros montants ?"

Nous pouvons répondre avec :

In [71]:
df.nlargest(10, "amount")[
    [
        "order_id",
        "country",
        "category",
        "quantity",
        "amount"
    ]
]

        order_id  country     category  quantity     amount
3388  ORD-001711    Spain  Electronics       185  218816.15
1584  ORD-003530    Spain  Electronics       138  129579.24
2009  ORD-003897  Germany        Books         7   82978.84
2943  ORD-001005    Italy  Electronics       122   54496.18
4764  ORD-001528    Italy  Electronics         4   49810.68
4938  ORD-004888  Belgium         Home        89   44500.00
4921  ORD-003100  Germany     Clothing         2   28278.12
817   ORD-000176    Spain       Sports         5   27799.10
226   ORD-000374   France     Clothing         2   27570.10
4922  ORD-002279  Germany     Clothing        90   21909.60

Nous commençons déjà à transformer une question métier en opération Pandas.

# 46. Explorer les méthodes de paiement

In [72]:
df["payment_method"].value_counts()

payment_method
Credit Card      2444
PayPal           1272
Bank Transfer     763
Apple Pay         536
Name: count, dtype: int64

Puis :

In [73]:
df["payment_method"].value_counts(
    normalize=True
)

payment_method
Credit Card      0.487338
PayPal           0.253639
Bank Transfer    0.152144
Apple Pay        0.106879
Name: proportion, dtype: float64

# 47. Explorer les notes clients

In [74]:
df["customer_rating"].value_counts()

customer_rating
5.0    1861
4.0    1360
3.0     754
2.0     422
1.0     218
Name: count, dtype: int64

Attention :

`customer_rating` est une variable numérique, mais elle peut également être considérée comme une variable **ordinale**.

Une note de :

```text
1 < 2 < 3 < 4 < 5
```

a un ordre.

Mais la différence entre 1 et 2 n'est pas nécessairement équivalente à celle entre 4 et 5.

# 48. Une première analyse croisée

Nous pouvons demander :

> Combien de commandes avons-nous par pays et par catégorie ?

In [75]:
df[
    ["country", "category"]
].value_counts()

country       category
France        Electronics    435
              Clothing       420
              Home           322
              Books          289
              Sports         264
Germany       Clothing       232
              Electronics    232
Spain         Electronics    197
Germany       Home           194
Spain         Clothing       185
              Home           170
Italy         Electronics    160
Germany       Books          156
              Sports         146
Italy         Clothing       143
              Home           127
Belgium       Clothing       124
              Electronics    108
Spain         Sports         106
Netherlands   Electronics    104
Spain         Books          100
Belgium       Home            99
Italy         Sports          95
              Books           94
Belgium       Sports          93
Netherlands   Home            79
              Clothing        73
              Books           69
Belgium       Books           61
Netherlands   Sports          58
France        home             2
 Spain        Clothing         2
 Netherlands  Home             2
Germany       clothing         2
Italy         clothing         1
Netherlands   electronics      1
              home             1
 Belgium      Books            1
France        sports           1
Germany       electronics      1
 Netherlands  Clothing         1
 France       Books            1
              Electronics      1
              Home             1
 Germany      Sports           1
 Italy        Clothing         1
              Sports           1
 Netherlands  Electronics      1
Germany       books            1
 Spain        Sports           1
Belgium       electronics      1
              sports           1
France        clothing         1
              electronics      1
 Belgium      Electronics      1
Spain         clothing         1
Name: count, dtype: int64

Nous commençons ici à croiser plusieurs variables.

Nous verrons plus tard comment effectuer des analyses beaucoup plus puissantes avec `groupby()`.

# 49. Un autre exemple

Combien de commandes françaises utilisent chaque moyen de paiement ?

In [76]:
df[
    df["country"] == "France"
]["payment_method"].value_counts()

payment_method
Credit Card      839
PayPal           458
Bank Transfer    270
Apple Pay        174
Name: count, dtype: int64

Décomposons mentalement :

```text
df
 │
 ↓
filtrer France
 │
 ↓
sélectionner payment_method
 │
 ↓
compter les valeurs
```

C'est une manière très importante de penser Pandas :

> **enchaîner des opérations simples pour répondre à une question métier.**

# 50. Le chaînage d'opérations

Par exemple :

In [77]:
df[
    df["country"] == "France"
]["amount"].mean()

np.float64(796.7805858701895)

Lecture :

```text
DataFrame
   ↓
commandes françaises
   ↓
colonne amount
   ↓
moyenne
```

# 51. Un exemple plus complexe

Question :

> Quel est le montant moyen des commandes françaises contenant au moins 2 produits ?

In [78]:
df[
    (df["country"] == "France")
    & (df["quantity"] >= 2)
]["amount"].mean()

np.float64(1083.9240860215052)

Nous combinons :

* filtrage ;
* conditions multiples ;
* sélection de colonne ;
* agrégation.

# 52. Construire une checklist d'exploration

Face à un nouveau dataset, vous pouvez utiliser cette checklist.

### Structure

In [79]:
df.shape
df.columns
df.head()
df.tail()

,order_id,customer_id,order_date,country,category,quantity,unit_price,discount,payment_method,customer_rating,amount
5010,ORD-004427,CUST-00386,2025-11-19 03:36:00,France,Books,1,37.46,0.15,PayPal,5.0,37.46
5011,ORD-000467,CUST-00249,2025-02-19 22:32:00,Germany,Sports,3,229.10,0.05,Credit Card,4.0,687.30
5012,ORD-003093,CUST-01079,2024-07-16 17:48:00,Germany,clothing,1,178.44,0.00,Bank Transfer,5.0,178.44
5013,ORD-003773,CUST-00792,2025-07-08 05:15:00,Spain,Electronics,2,1200.00,0.00,Credit Card,5.0,2400.00
5014,ORD-000861,CUST-01453,2024-01-10 05:41:00,Germany,Clothing,1,183.05,0.05,Bank Transfer,5.0,183.05

### Types

In [80]:
df.dtypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5015 entries, 0 to 5014
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         5015 non-null   object
 1   customer_id      5015 non-null   object
 2   order_date       5015 non-null   object
 3   country          4995 non-null   object
 4   category         4985 non-null   object
 5   quantity         5015 non-null   int64
 6   unit_price       5015 non-null   float64
 7   discount         5015 non-null   float64
 8   payment_method   5015 non-null   object
 9   customer_rating  4615 non-null   float64
 10  amount           5015 non-null   float64
dtypes: float64(4), int64(1), object(6)
memory usage: 431.1+ KB

### Statistiques

In [81]:
df.describe()

          quantity    unit_price     discount  customer_rating         amount
count  5015.000000   5015.000000  5015.000000      4615.000000    5015.000000
mean      2.761117    322.170449     0.064148         3.915276     943.374802
std       4.957655    538.134329     0.074894         1.162172    4170.569059
min       1.000000      8.000000     0.000000         1.000000      11.420000
25%       1.000000     98.325000     0.000000         3.000000     179.950000
50%       2.000000    210.230000     0.050000         4.000000     419.340000
75%       4.000000    400.000000     0.100000         5.000000     995.660000
max     185.000000  14139.060000     0.300000         5.000000  218816.150000

### Variables catégorielles

In [84]:
df["country"].unique()

array(['Germany', 'Italy', 'Belgium', 'Netherlands', 'France', 'Spain',
       ' Netherlands', nan, ' Belgium', ' Spain', ' Italy', ' France',
       ' Germany'], dtype=object)

In [85]:
df["country"].nunique()

12

In [86]:
df["country"].value_counts()

country
France          1741
Germany          970
Spain            766
Italy            625
Belgium          490
Netherlands      388
 Netherlands       4
 Spain             3
 France            3
 Belgium           2
 Italy             2
 Germany           1
Name: count, dtype: int64

### Valeurs manquantes

In [87]:
df.isna().sum()

order_id             0
customer_id          0
order_date           0
country             20
category            30
quantity             0
unit_price           0
discount             0
payment_method       0
customer_rating    400
amount               0
dtype: int64

### Doublons

In [88]:
df.duplicated().sum()

np.int64(15)

### Valeurs extrêmes

In [89]:
df["unit_price"].min()

8.0

In [90]:
df["unit_price"].max()

14139.06